export const homeFAQs=[
 ['Where should we begin planning an Indian wedding?','Start with five shared decisions: priorities, a comfortable budget range, guest estimate, location and the events that matter to your families.'],
 ['Does every Hindu wedding follow the same ceremonies?','No. Ceremony names, sequences and meanings vary by region, community and family. Confirm religious details with your priest, pandit, officiant or elders.'],
 ['How early should we book wedding vendors?','Popular venues and priority vendors are often considered 9 to 12 months ahead, but availability varies. Compare written quotations and contracts before paying deposits.'],
 ['Can the budget calculator include several events?','Yes. Enter combined costs, or estimate events separately when guest counts differ and then add the relevant totals together.'],
 ['May we adapt the invitation wording examples?','Yes. Personalise every example with your names, hosts, event details and family voice, then proofread carefully before sending.']
];

const icons={
 plan:'<path d="M7 6.5h18v21H7zM11 3v7M21 3v7M11 15h10M11 20h7"/>',
 ceremony:'<path d="M16 4c4 4 7 8 7 13a7 7 0 1 1-14 0c0-5 3-9 7-13Zm0 8c-2 3-3 5-3 7a3 3 0 0 0 6 0c0-2-1-4-3-7ZM7 28h18"/>',
 region:'<path d="M16 29s9-8 9-16a9 9 0 1 0-18 0c0 8 9 16 9 16Zm0-12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z"/>',
 budget:'<path d="M16 4v24M22 9c-2-3-12-3-12 2 0 6 12 3 12 9 0 5-10 5-13 1M5 4h22v24H5z"/>',
 invite:'<path d="M4 8h24v17H4zM4 9l12 9L28 9M10 5h12"/>',
 bridal:'<path d="M16 5c-3 0-5 2-5 5s2 5 5 5 5-2 5-5-2-5-5-5Zm-8 23c1-7 4-11 8-11s7 4 8 11M12 20l4 3 4-3"/>',
 groom:'<path d="M16 5c-3 0-5 2-5 5s2 5 5 5 5-2 5-5-2-5-5-5Zm-8 23c1-7 4-11 8-11s7 4 8 11M12 18l4 4 4-4M16 22v6"/>',
 food:'<path d="M5 18h22M8 18a8 8 0 0 1 16 0M16 10V7M4 23h24M7 28h18"/>',
 decor:'<path d="M16 4v24M8 11c4 0 6-3 8-7 2 4 4 7 8 7-4 0-6 3-8 7-2-4-4-7-8-7ZM7 28h18"/>'
};
const icon=name=>`<svg class="category-svg" viewBox="0 0 32 32" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${icons[name]}</svg>`;

export function createPhase1BHome({ad,faqs}){
 const categories=[
  ['plan','Wedding Planning','Timelines & checklists','wedding-planning.html'],['ceremony','Hindu Ceremonies','Rituals with context','hindu-wedding-ceremonies.html'],['region','Regional Weddings','Traditions across India','regional-weddings.html'],['budget','Budget Tools','Estimate costs in INR','wedding-tools.html'],['invite','Invitation Wording','Original examples','invitation-wording.html'],['bridal','Bridal Guide','Attire & preparation','wedding-planning.html#final-30-days'],['groom','Groom Guide','Attire & responsibilities','wedding-planning.html#wedding-week'],['food','Wedding Food','Menus & guest care','wedding-planning.html#guest-experience'],['decor','Wedding Decorations','Décor briefs & budgets','wedding-planning.html#guest-experience']
 ];
 const ceremonies=[['Haldi','haldi-ceremony.html','Sunlit blessings'],['Mehndi','mehndi-ceremony.html','Art and celebration'],['Sangeet','hindu-wedding-ceremonies.html#sangeet','Music with family'],['Baraat','hindu-wedding-ceremonies.html#baraat','A joyful arrival'],['Varmala','hindu-wedding-ceremonies.html#jaimala-or-varmala','Garlands exchanged'],['Saptapadi','hindu-wedding-ceremonies.html#saptapadi','Seven shared steps']];
 const timeline=[['12 months','Priorities, budget, guest range and location'],['9 months','Venues, priority vendors and attire research'],['6 months','Invitations, ceremonies, décor and travel'],['3 months','Menus, fittings, music and family roles'],['Final month','Counts, payments, transport and run sheets'],['Wedding week','Contacts, event packing, meals and rest']];
 return `<section class="home-hero phase1c-hero"><div class="hero-motif motif-left" aria-hidden="true"></div><div class="hero-copy"><p class="eyebrow">Indian wedding planning, made calmer</p><h1>Your Indian Wedding,<br><em>Beautifully Planned</em></h1><p>Clear, culturally respectful guidance for planning a celebration that feels true to your family—from the first guest-list conversation to the final vidaai.</p><div class="hero-actions"><a class="button" href="wedding-planning.html">Start Planning</a><a class="button secondary" href="wedding-budget-calculator.html">Calculate Your Budget</a></div><ul class="hero-proof" aria-label="ShaadiGuide benefits"><li>Practical checklists</li><li>Respectful guidance</li><li>Free planning tools</li></ul></div><figure class="hero-illustration"><img src="assets/images/hero-wedding.webp" width="864" height="582" loading="eager" decoding="async" alt="Illustration of an Indian bride and groom beneath a decorated wedding mandap"></figure></section>
 <section class="search-trust-wrap"><div class="search-band" aria-labelledby="search-title"><div class="search-intro"><p class="eyebrow">Find your next step</p><h2 id="search-title">Search ShaadiGuide</h2></div><form class="site-search" role="search" data-search><span class="search-symbol" aria-hidden="true"></span><label class="sr-only" for="home-search">Search ShaadiGuide</label><input id="home-search" type="search" placeholder="Search ceremonies, traditions, budgets and invitations" autocomplete="off" aria-autocomplete="list" aria-controls="search-results" aria-expanded="false"><button type="submit">Search</button><div class="search-results" id="search-results" role="listbox" hidden></div></form><p class="search-hint">Try: Haldi, Mehndi, Punjabi wedding, budget calculator or WhatsApp invitation</p></div><aside class="trust-card"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M20 3 34 8v10c0 9-6 15-14 19C12 33 6 27 6 18V8Z"/><path d="M13 20c4 0 6-3 7-7 1 4 3 7 7 7-4 0-6 3-7 7-1-4-3-7-7-7Z"/></svg><div><h2>Culturally Respectful Guidance</h2><p>Traditions vary. Confirm religious and family details with your pandit, officiant or elders.</p></div></aside></section>
 <section class="home-container category-section"><div class="section-kicker"><p class="eyebrow">Explore by category</p><h2>Everything you need to plan with confidence</h2></div><div class="category-grid">${categories.map(([ic,t,d,u])=>`<a class="category-card" href="${u}">${icon(ic)}<span><strong>${t}</strong><small>${d}</small></span><b aria-hidden="true">→</b></a>`).join('')}</div></section>
 ${ad('home-ad')}
 <section class="home-container featured-dashboard"><article class="feature-panel ceremony-panel"><header><div><p class="eyebrow">Popular ceremonies</p><h2>Celebrate with understanding</h2></div><a href="hindu-wedding-ceremonies.html">View all →</a></header><div class="ceremony-mini-grid">${ceremonies.map(([t,u,d],i)=>`<a href="${u}"><span class="ceremony-art art-${i+1}" aria-hidden="true"><i></i></span><div><h3>${t}</h3><p>${d}</p></div></a>`).join('')}</div></article><article class="feature-panel timeline-panel"><header><div><p class="eyebrow">Planning timeline</p><h2>A calmer countdown</h2></div><a href="wedding-planning.html">Full checklist →</a></header><ol>${timeline.map(([t,d],i)=>`<li><span>0${i+1}</span><div><b>${t}</b><p>${d}</p></div></li>`).join('')}</ol></article><article class="feature-panel tools-panel"><p class="eyebrow">Budget tools</p><h2>Plan the numbers clearly</h2><p>Build INR estimates, compare categories and print useful family summaries.</p><a class="tool-primary" href="wedding-budget-calculator.html"><span>₹</span><div><strong>Wedding Budget Calculator</strong><small>Working browser-based tool</small></div><b aria-hidden="true">→</b></a><ul><li><a href="catering-cost-calculator.html">Catering Calculator</a> <em>Working tool</em></li><li><a href="cost-per-guest-calculator.html">Cost per Guest Calculator</a> <em>Working tool</em></li><li><a href="venue-budget-calculator.html">Venue Budget Calculator</a> <em>Working tool</em></li><li><a href="decoration-budget-calculator.html">Decoration Budget Calculator</a> <em>Working tool</em></li></ul></article></section>
 <section class="home-container quick-row"><a href="invitation-wording.html"><span>01</span><div><p class="eyebrow">Invitation wording</p><h2>Find the right words</h2><p>Traditional, modern, WhatsApp and reception-only examples.</p></div></a><a href="#featured-guides"><span>02</span><div><p class="eyebrow">Featured guides</p><h2>Read what matters now</h2><p>Useful ceremony and planning guides already available.</p></div></a><a href="wedding-planning.html"><span>03</span><div><p class="eyebrow">Plan your wedding</p><h2>Begin with five decisions</h2><p>Bring both families around a clear and comfortable plan.</p></div></a><a href="#faqs"><span>04</span><div><p class="eyebrow">Helpful answers</p><h2>Questions families ask</h2><p>Practical answers with cultural variation kept in view.</p></div></a></section>
 <section class="wide-section regional-feature"><div class="home-container"><div class="section-head"><div><p class="eyebrow">Across India</p><h2>Regional traditions, respectfully introduced</h2></div><a class="section-link" href="regional-weddings.html">Explore regional weddings →</a></div><div class="region-row">${['Punjabi','Gujarati','Bengali','Marathi','Tamil','Telugu'].map((x,i)=>`<a href="regional-weddings.html#${x.toLowerCase()}"><small>0${i+1}</small>${x}<span>Explore tradition →</span></a>`).join('')}</div><p class="variation-note">Practices vary by locality, community and family. Begin with our introductions, then confirm the details that belong to yours.</p></div></section>
 <section class="home-container invitation-editorial"><div><p class="eyebrow">Invitation wording</p><h2>Words that sound like your family</h2><p>Adapt original examples for a traditional Hindu invitation, a modern celebration, a warm WhatsApp message or a reception-only event.</p><a class="button secondary" href="invitation-wording.html">Browse Wording Examples</a></div><blockquote><span aria-hidden="true">“</span>With the blessings of our families and the grace of the Divine, we invite you to share in the joy of our wedding celebration.<small>Traditional wording example</small></blockquote></section>
 ${ad('home-ad')}
 <section class="home-container featured-guides" id="featured-guides"><div class="section-head"><div><p class="eyebrow">Featured guides</p><h2>Useful reads for your planning list</h2></div></div><div class="guide-grid"><a href="haldi-ceremony.html"><span>01</span><div><p class="eyebrow">Ceremony guide</p><h3>Plan a warm, comfortable Haldi</h3><p>Timing, clothing, food, décor and photography.</p></div></a><a href="mehndi-ceremony.html"><span>02</span><div><p class="eyebrow">Celebration guide</p><h3>Create a better Mehndi timeline</h3><p>Artists, seating, lighting and guest comfort.</p></div></a><a href="wedding-planning.html"><span>03</span><div><p class="eyebrow">Planning guide</p><h3>Make the first five decisions</h3><p>Priorities, budget, guests, location and format.</p></div></a></div></section>
 <section class="home-container home-faq">${faqs(homeFAQs)}</section>
 <section class="planning-reminder"><div><p class="eyebrow">Plan with clarity</p><h2>Get Planning Tips & Checklists</h2><p>Start with the complete wedding planning guide today. Downloadable resources are coming in a future phase—there is no inactive signup form to complete.</p></div><div><span>Printable resources · Coming soon</span><a class="button" href="wedding-planning.html">Start Planning</a></div></section>`;
}
