import fs from 'node:fs';

const slugs=['delhi','mumbai','bengaluru','hyderabad','chennai','kolkata','ahmedabad','pune','jaipur','udaipur','jodhpur','lucknow','chandigarh','amritsar','surat','vadodara','indore','bhopal','patna','bhubaneswar','guwahati','kochi','thiruvananthapuram','coimbatore','mysuru','visakhapatnam','vijayawada','nagpur','nashik','goa','shimla','dehradun','rishikesh','varanasi','prayagraj','agra','gurugram','noida','raipur','ranchi'];
const files=slugs.map(x=>`${x}-wedding-planning-guide.html`);const errors=[];
for(const file of files){const html=fs.readFileSync(file,'utf8');for(const token of ['city-wedding-guides.html','Planning a wedding in','Why couples may consider the city','Local wedding styles and venue categories','Indoor versus outdoor planning','Seasonal and weather considerations','Guest travel, railway and airport planning','Accommodation and local transport','Ceremony and regional-tradition considerations','Catering, decoration and photography','Vendor-booking timeline','Budget categories','Practical city checklist','Common mistakes','wedding-venue-guide.html','accommodation-planner.html','transportation-cost-calculator.html','wedding-checklists.html','"@type":"Article"','"@type":"BreadcrumbList"','"@type":"FAQPage"'])if(!html.toLowerCase().includes(token.toLowerCase()))errors.push(`${file}: missing ${token}`);for(const banned of ['LocalBusiness','aggregateRating','reviewCount','best wedding city','₹','Rs.','per plate starting'])if(html.includes(banned))errors.push(`${file}: prohibited claim or schema ${banned}`)}
const hub=fs.readFileSync('city-wedding-guides.html','utf8');for(const file of files)if(!hub.includes(`href="${file}"`))errors.push(`city hub missing ${file}`);for(const filter of ['north','south','east','west','central','northeast','metro','heritage','coastal','hill','destination'])if(!hub.includes(`data-city-filter="${filter}"`))errors.push(`city hub missing filter ${filter}`);
const search=fs.readFileSync('assets/js/city-search-data.js','utf8');for(const file of files)if(!search.includes(`"url":"${file}"`))errors.push(`city search missing ${file}`);for(const synonym of ['Bangalore','Cochin','Trivandrum','Mysore','Allahabad'])if(!search.includes(synonym))errors.push(`city search missing synonym ${synonym}`);
const sitemap=fs.readFileSync('sitemap.xml','utf8');for(const file of ['city-wedding-guides.html',...files])if(!sitemap.includes(`https://shaadiguide.in/${file}`))errors.push(`sitemap missing ${file}`);
if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log('PASS: city hub and 40 guides include Phase 14 logistics, cross-links, schema, search synonyms, filters and sitemap coverage without listings or invented prices.');
