import fs from 'node:fs';import vm from 'node:vm';
const fail=[];
// Invitation filter: search and category button both alter visible cards.
const cards=[{textContent:'Haldi Invitation',dataset:{types:'pre-wedding whatsapp'},hidden:false},{textContent:'Reception Invitation',dataset:{types:'reception wedding'},hidden:false}];const input={value:'',h:{},addEventListener(t,f){this.h[t]=f}};const status={textContent:''};const buttons=['all','pre-wedding','reception'].map(v=>({dataset:{invitationFilter:v},h:{},addEventListener(t,f){this.h[t]=f},setAttribute(){}}));const filterDoc={querySelectorAll:s=>s==='[data-invitation-card]'?cards:buttons,querySelector:s=>s==='[data-invitation-search]'?input:status};vm.runInNewContext(fs.readFileSync('assets/js/invitations/invitation-filter.js','utf8'),{document:filterDoc});input.value='Haldi';input.h.input();if(!(!cards[0].hidden&&cards[1].hidden))fail.push('invitation text filter failed');input.value='';buttons[2].h.click();if(!(cards[0].hidden&&!cards[1].hidden))fail.push('invitation category filter failed');
// Generator: all fields, blanks and markup-like characters remain text, never HTML.
const values={eventType:'wedding',hostingStyle:'together with their families',coupleNames:'Asha <script> & Dev',familyNames:'',date:'15 January',time:'6:00 pm',venue:'Lotus <Hall>',city:'Pune',rsvpName:'Mira',rsvpDeadline:'1 January',dressCode:'Indian formal',noGifts:'yes',tone:'warm'};const elements=Object.fromEntries(Object.entries(values).map(([k,v])=>[k,{value:v}]));const form={elements,h:{},querySelectorAll:()=>[],addEventListener(t,f){this.h[t]=f}};let usedInnerHTML=false;const output={_text:'',set textContent(v){this._text=v},get textContent(){return this._text},set innerHTML(v){usedInnerHTML=true}};const printButton={addEventListener(){}};const builder={querySelector:s=>s==='form'?form:s==='[data-generator-output]'?output:s==='[data-generator-print]'?printButton:null};const generatorDoc={querySelector:s=>s==='[data-invitation-generator]'?builder:null};vm.runInNewContext(fs.readFileSync('assets/js/invitations/invitation-generator.js','utf8'),{document:generatorDoc,setTimeout,window:{print(){}}});form.h.input();if(!output.textContent.includes('Asha <script> & Dev')||!output.textContent.includes('Lotus <Hall>')||usedInnerHTML)fail.push('generator safe text handling failed');for(const k of ['date','time','venue','city','rsvpName','rsvpDeadline','dressCode'])elements[k].value='';form.h.input();if(/[·,]\s*\n/.test(output.textContent)||output.textContent.includes('undefined'))fail.push('generator blank optional-field handling failed');
for(const eventType of ['wedding','reception','engagement','haldi','mehndi','sangeet'])for(const tone of ['warm','traditional','formal','modern','casual']){elements.eventType.value=eventType;elements.tone.value=tone;form.h.input();if(!output.textContent.trim()||output.textContent.includes('undefined'))fail.push(`generator failed for ${eventType}/${tone}`)}
// Checklist progress and both reset controls.
const boxes=[{checked:false,h:{},addEventListener(t,f){this.h[t]=f}},{checked:false,h:{},addEventListener(t,f){this.h[t]=f}}];const progress={textContent:''};const reset={h:{},addEventListener(t,f){this.h[t]=f}};const print={addEventListener(){}};const scope={querySelector:s=>s==='[data-progress]'?progress:null,querySelectorAll:s=>s==='[data-checklist-reset]'?[reset]:s==='[data-checklist-print]'?[print]:[],style:{setProperty(){}}};const root={querySelectorAll:()=>boxes,closest:()=>scope};const checklistDoc={querySelectorAll:()=>[root]};vm.runInNewContext(fs.readFileSync('assets/js/checklists/checklist-progress.js','utf8'),{document:checklistDoc,window:{print(){}}});boxes[0].checked=true;boxes[0].h.change();if(progress.textContent!=='1 of 2 completed')fail.push('checklist progress failed');reset.h.click();if(progress.textContent!=='0 of 2 completed'||boxes.some(x=>x.checked))fail.push('checklist reset failed');
const copySource=fs.readFileSync('assets/js/invitations/copy-wording.js','utf8');for(const token of ['navigator.clipboard','window.isSecureContext','document.execCommand','textContent'])if(!copySource.includes(token))fail.push(`copy fallback missing ${token}`);if(fail.length){console.error(fail.join('\n'));process.exit(1)}console.log('PASS: invitation filtering, safe generator output, blank fields, checklist progress/reset and file:// copy fallback verified.');
