import fs from 'node:fs';import vm from 'node:vm';const failures=[];
// Multi-dimensional hub filter.
const cards=[{dataset:{speaker:'couple',occasion:'vows',tone:'warm',length:'short'},hidden:false},{dataset:{speaker:'parents',occasion:'blessing',tone:'formal',length:'short'},hidden:false}];const controls=['speaker','occasion','tone','length'].map(name=>({name,value:'all',h:{},addEventListener(t,f){this.h[t]=f}}));const status={textContent:''};const filterDoc={querySelectorAll:s=>s==='[data-message-card]'?cards:controls,querySelector:()=>status};vm.runInNewContext(fs.readFileSync('assets/js/messages/speech-filter.js','utf8'),{document:filterDoc});controls[0].value='parents';controls[0].h.change();if(!(cards[0].hidden&&!cards[1].hidden&&status.textContent==='1 resource shown.'))failures.push('speech filter failed');
function runBuilder(file,rootSelector,values){const elements=Object.fromEntries(Object.entries(values).map(([k,v])=>[k,{value:v}]));const form={elements,h:{},addEventListener(t,f){this.h[t]=f}};let inner=false;const output={_v:'',set textContent(v){this._v=v},get textContent(){return this._v},set innerHTML(v){inner=true}};const button={addEventListener(){}};const root={querySelector:s=>s==='form'?form:s==='[data-builder-output]'?output:button};const document={querySelector:s=>s===rootSelector?root:null};vm.runInNewContext(fs.readFileSync(file,'utf8'),{document,setTimeout,window:{print(){}}});form.h.input();return{elements,form,output,inner}}
const speech=runBuilder('assets/js/messages/speech-builder.js','[data-speech-builder]',{speakerRole:'sibling',relationship:'sister',coupleNames:'Asha <script> & Dev',tone:'warm',length:'2 minutes',memory:'a rainy train journey',qualities:'patience and humour',thanks:'our families',closing:'toast'});if(speech.inner||!speech.output.textContent.includes('Asha <script> & Dev'))failures.push('speech builder unsafe output');speech.elements.memory.value='';speech.elements.qualities.value='';speech.elements.thanks.value='';speech.form.h.input();if(/undefined|null/.test(speech.output.textContent))failures.push('speech builder blank optional fields failed');
const vows=runBuilder('assets/js/messages/vow-builder.js','[data-vow-builder]',{coupleNames:'Mira & Sam',tone:'warm',length:'short',values:'kindness',goals:'build a welcoming home',promises:'share responsibility',family:'our families',memory:'',closing:'modern'});if(vows.inner||!vows.output.textContent.includes('Mira & Sam'))failures.push('vow builder failed');
const message=runBuilder('assets/js/messages/message-generator.js','[data-message-generator]',{occasion:'anniversary',relationship:'family',tone:'warm',names:'Ria <3 Jay',length:'long'});if(message.inner||!message.output.textContent.includes('Ria <3 Jay'))failures.push('message generator failed');
for(const role of ['bride','groom','parent','sibling','friend','host'])for(const tone of ['warm','formal','light','emotional','brief'])for(const length of ['1 minute','2 minutes','3 minutes','5 minutes']){speech.elements.speakerRole.value=role;speech.elements.tone.value=tone;speech.elements.length.value=length;speech.form.h.input();if(!speech.output.textContent.includes(length)||!speech.output.textContent.trim())failures.push(`speech option failed: ${role}/${tone}/${length}`)}
for(const tone of ['warm','formal','modern','light'])for(const length of ['short','medium','long']){vows.elements.tone.value=tone;vows.elements.length.value=length;vows.form.h.input();if(!vows.output.textContent.trim()||/undefined|null/.test(vows.output.textContent))failures.push(`vow option failed: ${tone}/${length}`)}
for(const occasion of ['congratulations','anniversary','thanks','engagement','unable','home','blessing'])for(const tone of ['warm','formal','brief'])for(const length of ['short','long']){message.elements.occasion.value=occasion;message.elements.tone.value=tone;message.elements.length.value=length;message.form.h.input();if(!message.output.textContent.includes('Ria <3 Jay')||/undefined|null/.test(message.output.textContent))failures.push(`message option failed: ${occasion}/${tone}/${length}`)}
const copy=fs.readFileSync('assets/js/messages/copy-example.js','utf8');for(const token of ['navigator.clipboard','window.isSecureContext','document.execCommand','textContent'])if(!copy.includes(token))failures.push(`copy fallback missing ${token}`);for(const file of ['wedding-speech-builder.html','wedding-vow-builder.html','wedding-message-generator.html']){const html=fs.readFileSync(file,'utf8');if(!html.includes('type="reset"')||!html.includes('data-builder-print'))failures.push(`${file}: reset or print missing`)}if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('PASS: speech filtering, three safe builders, blank optional fields, reset/print hooks and file:// copy fallback verified.');
