import fs from 'node:fs';

const established=['wedding-venue-guide.html','wedding-planner-guide.html','wedding-photographer-guide.html','wedding-videographer-guide.html','wedding-makeup-artist-guide.html','wedding-decorator-guide.html','wedding-florist-guide.html','wedding-caterer-guide.html','wedding-band-dj-guide.html','wedding-transport-guide.html','wedding-cake-dessert-guide.html','bridal-jewellery-guide.html','bridal-outfit-guide.html','groom-outfit-guide.html'];
const added=['groom-styling-guide.html','wedding-priest-pandit-guide.html','live-wedding-music-guide.html','wedding-invitation-vendor-guide.html','wedding-gifts-guide.html','luxury-wedding-car-guide.html','honeymoon-planning-guide.html'];
const errors=[];
for(const file of added){const html=fs.readFileSync(file,'utf8');for(const token of ['page-hero','What this service does','How to choose the right option','Questions to ask before booking','Budget considerations','Common mistakes','Typical booking timeline','Booking checklist','Do’s and don’ts','wedding-planning.html','hindu-wedding-ceremonies.html','regional-weddings.html','wedding-tools.html','vendor-question-checklist.html','"@type":"Article"','"@type":"BreadcrumbList"','"@type":"FAQPage"'])if(!html.toLowerCase().includes(token.toLowerCase()))errors.push(`${file}: missing ${token}`);for(const banned of ['aggregateRating','reviewCount','affiliate.com','Book now'])if(html.includes(banned))errors.push(`${file}: prohibited vendor claim ${banned}`)}
for(const file of established){const html=fs.readFileSync(file,'utf8');for(const token of ['What this vendor does','Questions to ask before booking','Budget considerations','Typical planning timeline','Contract checklist','Warning signs','Comparison checklist','data-checklist','vendors.html','wedding-tools.html','wedding-checklists.html','regional-weddings.html'])if(!html.toLowerCase().includes(token.toLowerCase()))errors.push(`${file}: established category missing ${token}`)}
const hub=fs.readFileSync('vendors.html','utf8');for(const file of [...established,...added])if(!hub.includes(`href="${file}"`))errors.push(`vendor hub missing ${file}`);
const search=fs.readFileSync('assets/js/main.js','utf8');for(const file of added)if(!search.includes(`url:'${file}'`))errors.push(`search missing ${file}`);
const sitemap=fs.readFileSync('sitemap.xml','utf8');for(const file of added)if(!sitemap.includes(`https://shaadiguide.in/${file}`))errors.push(`sitemap missing ${file}`);
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log('PASS: all 21 requested vendor and venue categories are complete; seven new guides are covered by hub, search, sitemap and cross-link checks.');
